//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marshall.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.Proyectos_Prendas = new HashSet<Proyectos_Prendas>();
        }
    
        public int Id { get; set; }
        public string Nota { get; set; }
        public int Oci { get; set; }
        public Nullable<int> CantidaReal { get; set; }
        public Nullable<int> CantidadPendiente { get; set; }
        public Nullable<System.DateTime> EstimadoInicio { get; set; }
        public Nullable<System.DateTime> EstimadoFinalizado { get; set; }
        public Nullable<System.DateTime> RealInicio { get; set; }
        public Nullable<System.DateTime> RealFinalizado { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos_Prendas> Proyectos_Prendas { get; set; }
    }
}
